### ISSUE TITLE
show a loading message when starting up

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#246]
currently we show a blank screen, which can last a long time and lead to user to think the app isn't working. 

instead, show a spinner (maybe [angular-spinner](https://github.com/urish/angular-spinner)? please make it 300x300px, in center of the page with the text "Loading" under it

**Comment by ceoaliongroo** [comment]
@niryariv, I have to use another module 

![progres-bar](https://cloud.githubusercontent.com/assets/2622152/5627956/f2677c50-95a8-11e4-894e-5a2d75980e61.gif)

We could for publish like this if it ok for you, with out the Loading text 

Add the text need extra work to extend this module with another directive to add the text, because we use ``resolve`` of ``ui router``  we need progress icons based on ``$http interceptors``.

**Comment by niryariv** [comment]
if you can add the "loading" text and move the spinner above it (on center of the page), that'll be much better
